### ISSUE TITLE
Error  "cannot import 'vol1': no such pool available"

### ISSUE THREAD

**Issue by botranvan** [ewwhite/zfs-ha#14]
When I deploy for a HA Cluster and I installed zfs on 2 nodes done is `lb01` and `lb02`.
While I creating a zfs resource, i have an error "cannot import 'vol1': no such pool available" on `lb02` node although i run commands same as on both nodes.
And when i created a zfs resource, whole storage pool mounting by zfs become  unmount :'(

Help me, please!!!
Thank you!

**Comment by botranvan** [comment]
I was fixed error by create a new resource by run command:

    pcs resource create vol1 ZFS pool="vol1" \
    op start timeout="90" \
    op stop timeout="90" \
    --group=group-vol1

instead of:

    pcs resource create vol1 ZFS pool="vol1" importargs="-d /dev/mapper/" \
    op start timeout="90" \
    op stop timeout="90" \
    --group=group-vol1

Sorry for this!! =))

**Comment by ewwhite** [comment]
So, this is resolved?

**Comment by botranvan** [comment]
Yes, I done!
Thank you very much for that guide!
