### ISSUE TITLE
Question about fence_scsi

### ISSUE THREAD

**Issue by intentions** [ewwhite/zfs-ha#15]
Hello,

   I've got a question about the fence_scsi, I have a similar setup to yours but instead of everything being in one big pool I have two pools that are supposed to be in an active-active configuration (so one pool being exported from each head unless there is a problem with one of the heads).

for the fence_scsi do I create two different stonith objects (one for each pool) or one big stonith object for  both pools?

**Comment by ewwhite** [comment]
In this case, you would create multiple groups and associate a fence device with each pool.

You can set resource co-location constraints to pin each pool to the node you want, allowing failover of that workload to the other node.

```
 fence-vol1	(stonith:fence_scsi):	Started zfs3-node1
 Resource Group: group-vol1
     vol1	(ocf::heartbeat:ZFS):	Started zfs3-node1
     vol1-ip	(ocf::heartbeat:IPaddr2):	Started zfs3-node1
 fence-vol2	(stonith:fence_scsi):	Started zfs3-node2
 Resource Group: group-vol2
     vol2	(ocf::heartbeat:ZFS):	Started zfs3-node2
     vol2-ip	(ocf::heartbeat:IPaddr2):	Started zfs3-node2
```

**Comment by intentions** [comment]
Thanks!
