### ISSUE TITLE
JBOD Redundancy

### ISSUE THREAD

**Issue by terminet85** [ewwhite/zfs-ha#18]
What would be the best strategy in order to redound also he JBOD?

**Comment by ewwhite** [comment]
It depends upon how you design the pool, your raid level and your risk profile.

For instance, if you use RAID mirrors, you can arrange each side of the mirror into a different JBOD.

SAS cabling is important. Multipath is important. But in practice, the incidence of complete JBOD failure is rare.

**Comment by mwpastore** [comment]
Keep in mind that most JBODs have quite a bit of redundancy built into them: redundant power supplies, redundant I/O modules, etc. The only "single point of failure" is the backplane itself, i.e. the circuit board that the drives and I/O modules plug into.

**Comment by ewwhite** [comment]
Right, and at a certain scale, you have to rely on the track record of the storage enclosures. It's difficult to plan/spread your vdevs across multiple cabinets in a way that would sustain enclosure failures.
