### ISSUE TITLE
GPT-label instead of multipath

### ISSUE THREAD

**Issue by colttt** [ewwhite/zfs-ha#2]
Hello,

first, very very good howto!
But I would recommend to use GPT-Labels instead of multipath, because you hace 36characters to specify which disk in which enclosure it is, thats better to support if a disk failes.. for example: r1e12d7-SN1234567 = r=rack, e=enclosure, d=disk and the Serialnumber.. at first it is a little bit of work to get all these correct information, but if something fails it is good to act very fast.

best regards

**Comment by ewwhite** [comment]
The default is to use mpath or multipath/WWN devices. Drive location is going to be a function of your controller and enclosure setup, so there's no deterministic way to derive locations across the variety of potential configurations out there. 

Are GPT labels acceptable as zpool creation devices?

**Comment by colttt** [comment]
> Are GPT labels acceptable as zpool creation devices?
> Yes, its the same what you find here: /dev/disk/by-partlabel/

I know that the raidcontroller/enclosure don't say me in which bay is which Harddisk, but i can find it out and then this informations are very usefull.. you can blink the LED harddrives to find it out..
