### ISSUE TITLE
SLOG and L2ARC setup not described

### ISSUE THREAD

**Issue by severgun** [ewwhite/zfs-ha#21]
You describe hardware, but there is no description how to set them.

> Once there's some idea of the SAS address layout of the drives, we can create a zpool.
> ...
> The result:

BOOM!
cache spares logs
what? where? how?
Could it be added later? Should it be shared or hostbased?

**Comment by ewwhite** [comment]
Spares are just pool drives.

Cache can be shared (SAS) or independent (one per host).

Logs need to be shared SAS disks. 

I can look into updating this...

**Comment by severgun** [comment]
I understand this from other isssue here.
I mean there is no instructions how to set them up. Just result.
Also. What about using vdev_id.conf aliases? Is it acceptable?

**Comment by ewwhite** [comment]
What do you need help with?

**Comment by severgun** [comment]
Is it acceptable to use /dev/disk/by-vdev/*** names to create HA pool and in pcs?
/dev/disk/by-vdev/*** names generated based on vdev_id.conf
https://github.com/zfsonlinux/zfs/wiki/FAQ#selecting-dev-names-when-creating-a-pool
As I understand conf should be same on both head nodes.

**Comment by ewwhite** [comment]
I'd recommend /dev/mapper multipath devices for zpool creation.
