### ISSUE TITLE
Drive replacement

### ISSUE THREAD

**Issue by Tualua** [ewwhite/zfs-ha#22]
Hi!
I have a question. 
When I create stonith device with **pcs stonith create fence-vol1** I use SCSI-address, e,g, _35000c500236032f7_
What will happen when I need to replace faulty drive? Will SCSI address be the same or I will need to change stonith device?

Thanks!

**Comment by ewwhite** [comment]
Good question.

For the fencing to continue working, you will need to update the stonith to reflect the new drive's WWN and remove the old drive's WWN.

This can be done in the web GUI or by using a `pcs stonith update` command.

For example:
`pcs stonith update fence-vol1 fence_scsi pcmk_monitor_action="metadata" devices="/dev/mapper/35000c5005612a19b,/dev/mapper/35000c500560e98cb,/dev/mapper/35000cca01c49e3e0,/dev/mapper/35000c50055f463ef,/dev/mapper/35000c5005612d27f,/dev/mapper/35000c5005612dbd3,/dev/mapper/35000c50055f4d54f,/dev/mapper/35000c5005608023f,/dev/mapper/35000c50055f4c593,/dev/mapper/35000c50055f4d2c7,/dev/mapper/35000c500561126bb,/dev/mapper/35000a7203008dd91" meta provides=unfencing"`

**Comment by Tualua** [comment]
Thanks!
