### ISSUE TITLE
ssd drives

### ISSUE THREAD

**Issue by darklinkworker** [ewwhite/zfs-ha#23]
I am looking to make this zfs-ha but with a set of SSD instead. The idea is to have two enclosures one with stand HDD dual-port SAS drives and the other with a few SSD. The problem I am having is finding low cost dual port SDD. Is there a drive you recommended or a device I can insert to covert the common sata ssd to dual port sas? From my understanding sata drives won't allow the other node to be seen so then there is no redundancy if failure occured.

**Comment by ewwhite** [comment]
I typically use Micron SAS SSDs, as well as HP, HGST, SanDisk Optimus, Toshiba... whatever meets the capacity and price need. There are SATA->SAS interposers, but you should really plan on SAS drives.
