### ISSUE TITLE
Storage fencing with full NVME based setup

### ISSUE THREAD

**Issue by cu12** [ewwhite/zfs-ha#27]
Hi all,

I can see you use `fence_scsi` here, although I couldn't find any equivalent to do the same with NVME. Actually, I found that there's no fencing agent for NVME :/ https://bugzilla.redhat.com/show_bug.cgi?id=1700165  

Any ideas for this?

I have a two VMs setup with physical disks presented to them for ZFS.

**Comment by ewwhite** [comment]
I'm not sure what the design of your solution is. Can you describe it in better detail?

**Comment by cu12** [comment]
Hi @ewwhite I'm planning two create a simple two node setup, but instead of having scsi or ssd disks, mine are all nvme disks, where fence_scsi (or scsi equivalent translation methods) doesn't apply. Hope this made it a bit more clearer :)

**Comment by ewwhite** [comment]
How do you expect this to work?

**Comment by efschu** [comment]
For fencing I'm using fence_ipmilan, described here
https://github.com/efschu/AP-HA-CIAB-ISER/wiki
btw thanks @ewwhite for your guide, without yours mine would never have get written ;)
