### ISSUE TITLE
command and result are not the same

### ISSUE THREAD

**Issue by colttt** [ewwhite/zfs-ha#3]
Hello,

when ou create the zpool, you don't add a cache or log, but you zpool status -v show me that, maybe you forgott it or add it later?!

best regards

**Comment by ewwhite** [comment]
Yes, the cache and log devices were added later. This is highly dependent on the environment. Some people do not use cache or log devices in their ZFS configurations.

**Comment by colttt** [comment]
yes i know but when newbies will follow you tutorial and compare the input/output then there is a difference and they don't know why... ;)
