### ISSUE TITLE
iSCSI support

### ISSUE THREAD

**Issue by michelpy** [ewwhite/zfs-ha#32]
Hi there, great work !
I was wondering if one could add iSCSI target capabilities to this setup ? Willing to be the guinea pig.

I did read the closed issues, but this link no longer works :
https://bm-stor.com/index.php/blog/Linux-cluster-with-ZFS-on-Cluster-in-a-Box/
I have a few things that won't do NFS :-(

Thanks !

**Comment by ewwhite** [comment]
Here’s a cached copy of the old link:
https://web.archive.org/web/20180830025452/https://bm-stor.com/index.php/blog/Linux-cluster-with-ZFS-on-Cluster-in-a-Box/<https://web.archive.org/web/20180830025452/https:/bm-stor.com/index.php/blog/Linux-cluster-with-ZFS-on-Cluster-in-a-Box/>

**Comment by HuangShumin** [comment]
https://books.clusterapps.com/books/command-line/page/nfs-on-zfs-ha-cluster
