### ISSUE TITLE
Question about using a similar setup for FC Disk shelf connected directly to Qlogic FC HBA

### ISSUE THREAD

**Issue by brickcatena** [ewwhite/zfs-ha#35]
Thank you ewwhite for sharing your knowledge and experience with this stuff. Really helpful!

So not really an issue but more of a question or request for direction in regards to using this methodology with a fibre channel JBOD/ZFS Pool. 

My roadblock seems to be an issue with fence_scsi wanting features not supported by my setup. Specifically when the fence agent gets to the first sg_persist command it returns:
`sg_persist failed: Illegal request, Invalid opcode`

Not really having much experience with fencing, I guess my specific question would be is there different fence agent I could use instead? If so I would hope to find a working example online. Really just trying to put to good use a stack of hardware I already have.  My goal is to get one or more disk shelves connected to two controller nodes to allow for maintenance of the controllers and the redundancy that comes with that. I could abstract the controllers up a layer into VM's and do some kind of VM fencing if that helps but I would want to pass through the HBAs so I'm not sure that helps. Maybe fence_sbd? I'm open for ideas. Thanks for reading!!

The specific setup I am using:
1 x 25 Bay EMC VNGD disk shelf which has FC to SAS interposers for each disk, 2 2port hssdc2 4Gbit FC controllers in the shelf
25 Seagate ST910006CLAR1000 SAS drives with SPC-3 Compliance according to smartctl using FCP-2 transport protocol
2 Qlogic QLE2562 FC HBAs
2 Cisco UCS C240 M3 servers
Each host has 2 SFP to HSSDC2 style twinax cables connecting to the FC ports on the disk shelf
Active/Active multipath is working
Using a /dev/mapper/ multipath based zfs zpool

**Comment by scramatte** [comment]
Hi,

I've got similar requirement ... have you made any progress on it?

**Comment by ewwhite** [comment]
This is a fairly non-standard use case. But I supposed you could fence with IPMI or power instead.
I have no method to test against this type of setup.
