### ISSUE TITLE
Why not use iSCSI instead of SAS?

### ISSUE THREAD

**Issue by snaix** [ewwhite/zfs-ha#39]
Hi @ewwhite 

The zfs-ha is cool.  After reading the wiki,  I have an  idea about replacing SAS cable with ethernet cable, and use a iSCSI disk over LAN.

look at this image:
![image](https://user-images.githubusercontent.com/6660768/172614018-4da9a3be-902b-4d02-9688-ee99c520a63f.png)

If just replace SAS cable with ethernet cable, it seems everything is fine, they have same logic: just replace a cable type,  nothing changed on ZFS.
Of course, with iSCSI, there are more coupling, like NIC, Cable, Switch, and TCP congestion problem.
But blocks transmission over Ethernet provides more flexibility: we can use any server to be a ZFS head node, when the old one was crashed. And also, we can use an independent switch (and iscsi multi-path) for storage to avoid switch SPOF, congestion problem...

The performance problem doesn't seem serious at present: 10/25/100GE is more and more popular, faster than SAS3 12G.
And iSER...

So is there any problem with this idea?

**Comment by ewwhite** [comment]
Hello, 

This is definitely something you can explore. 
It's out of scope for this project, though.
