### ISSUE TITLE
How do you handle Replacing Disks and updating the Stonith Resource

### ISSUE THREAD

**Issue by nugsolot** [ewwhite/zfs-ha#7]
Thanks so much for your project here, its been an amazing template for me to layout something very similar and probably couldn't have gotten as far as I have without this.

A Few Questions or more maybe even just to get your thought on how you would handle these things:

When you think about a disk failing and needing to be replaced how do you handle the Stonith Resource update to reflected the changed disk?

Have you implemented smartd to watch the disks for failures that might come up?

brian

**Comment by ewwhite** [comment]
I have several methods of handling ZFS disk and pool health monitoring. 

My primary go-to is to install [zfswatcher](http://zfswatcher.damicon.fi), which provides all of the necessary pool and disk health alerts for ZFS deployments. Another option is to fully configure the ZED daemon by editing `/etc/zfs/zed.d/zed.rc` to taste. [Here's an example](https://www.reddit.com/r/zfs/comments/4zf5ji/first_disk_failure_on_my_linux_zfs/). Without modifying this, hot-spares will not work properly on ZFS.

Regarding updating STONITH resources when a drive fails, I make the change manually either by updating the STONITH pcs resource, or going into the Cluster Manager GUI (https://ip.address:2224) and adding the new drive's Device Mapper address to the list of disks in the STONITH setup.
