### ISSUE TITLE
Read access from both servers

### ISSUE THREAD

**Issue by AndersTrier** [ewwhite/zfs-ha#8]
If only serving static files, is it possible to do load balancing between two servers, and have both servers read from the disk shelf at the same time, if only one of them needs to write to the drives?

**Comment by redtex** [comment]
No, zfs pool can't be imported simultaneously on several nodes. Even in RO mode.

**Comment by ewwhite** [comment]
You can do this if you had multiple ZFS zpools and pin each to a different head node. But for the same pool, no.
