### ISSUE TITLE
systemd?

### ISSUE THREAD

**Issue by dmaziuk** [ewwhite/zfs-ha#9]
very nice write-up, thank you very much.

It might be worth spelling out that with (default install on centos 7.3 after the dependencies fix):
```
zfs.target
● ├─zfs-import-cache.service
● ├─zfs-mount.service
● ├─zfs-share.service
● └─zfs-zed.service
```
as long as you don't make a cache file, `zed` will start but no pools will be imported and nothing gets mounted or shared. But if the target include `zfs-import-scan.service`, things will break. (I assume -- I haven't tried.)

**Comment by ewwhite** [comment]
Thank you. I'll update to reflect that.

Should be something like:

`systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target`
